data_args:
  dataset: "cifar10"
  niid: 1

data_poison_attacks:
  blur: False
  label_flipping: True

model_poison_attacks:
  learning_rate_attack: False

learning_rate_attack:
  learning_rate_poison_value: 1

blur_parameters:
  kernal_size: 5
  sigma: 0.6

label_flipping_parameters:
  no_of_labels_to_flip: 10

model_args:
  model: "lenet"
  epochs: 1
  batch_size: 16
  learning_rate: 0.001
  device: 'gpu'  
  loss_function: cross_entropy

train_args:
  federated_algorithm: "fedavg"
  num_malicious_devices: 0
  client_num_in_total: 10
  comm_round: 5
  device: 'gpu'
  gpu_id: 1



phase:
  phase: 2